### ISSUE TITLE
Volcano not activating

### ISSUE THREAD

**Issue by cntrl-z-forlife** [2mal3/Natural-Disaster-Datapack#1]
When I try to run the volcano function, and it gives the error, "unknown function 2mal3:nadi/natural_disasters/volcano/eruption/1". I installed the datapack utils, and it still gave me this error. Am I doing something wrong, or is this a bug?

![Screen Shot 2021-09-09 at 10 54 55 AM](https://user-images.githubusercontent.com/80377189/132711943-8a3e5fb2-7694-4600-baa8-a75000b41a78.png)

**Comment by 2mal3** [comment]
You did nothing wrong, the problem was with the datapack. Thanks for the report!
The bug will be fixed in the next update, but for now, you can start a volcano eruption with the command `/function 2mal3:nadi/natural_disasters/volcano/eruption/find`.
